### ISSUE TITLE
@sentry/core/LICENSE must be under certain dir

### ISSUE THREAD

**Issue by tangb** [getsentry/sentry-electron#106]
Hi

It appear I can't build my electron application because of a problem of license file.
I don' understand the issue :S Is it a file in the bad place, a missing one, or something other.... 
```
Error: /home/osboxes/MyWonderfulApp/node_modules/@sentry/core/LICENSE must be under /home/osboxes/MyWonderfulApp/build/mywonderfulapp_tree/
    at AsarPackager.unpackPattern (/home/osboxes/MyWonderfulApp/node_modules/app-builder-lib/src/util/filter.ts:37:13)
    at /home/osboxes/MyWonderfulApp/node_modules/app-builder-lib/src/asar/asarUtil.ts:116:82
```
Can you help me ?

I'm using latest version 0.8.1 with electron 20.26.1.
Thx ;-)

**Comment by timfish** [comment]
Hi @tangb, can you describe your directory layout and how you're invoking `electron-builder`? 

It looks like your `node_modules` directory is not in you project directory. If you're using lerna or yarn workspaces, there is [this open issue](https://github.com/electron-userland/electron-builder/issues/2962) for `electron-builder` which might be relevant.

**Comment by tangb** [comment]
Hello @timfish 
My setup is a little bit complicated, my app backend is in python for some technical reasons.
So i build my python application with pyinstaller into build/app_tree dir, then copy all my electron stuff in that dir (license.txt, html dir, resources, app.js, readme and package.js)
Finally I package all of this using this command line:
`node_modules/.bin/electron-builder --mac --x64 --projectDir "$APPPATH"`
Another point is I don't use neither lerna nor yarn, but only npm.

I took a look in issue you mentioned and compilation succeed removing asarUnpack entry.
But my electron app launches the python bin that is in specific directory due to asar. So if asar is disabled my app doesn't work without some major changes.

For now I don't find a valid workaround :(

**Comment by timfish** [comment]
@tangb The referenced `electron-builder` bug has apparently been fixed in 20.28.2. Could you try that and let me know if it fixes your issue?

**Comment by VelGenov** [comment]
I'm experiencing a similar problem. I'm building all my targets on a OSX, and this started happening when I added Sentry.io to my project. The problem is very specific to building the Windows MSI target, and it's not fixed in the patch linked above. My exact configuration is below.

OSX: 10.14.3
electron-builder version: 20.38.5
sentry/cli version: 1.39.0
sentry/electron version: 0.15.0
sentry/webpack-plugin version: 1.6.2

This is the error I get:

`error output:Z:\Users\Vel\Documents\Projects\electron-desktop\release\__msi-ia32\project.wxs(154) : error LGHT0103 : The system cannot find the file 'Z:\Users\Vel\Documents\Projects\electron-desktop\release\win-ia32-unpacked\resources\app.asar.unpacked\node_modules\@sentry\cli\LICENSE'.`
